Repository jeremy0405/airbnb, pull requests merged in 2022-06, with the labels that each got.

#43 [BE] - GET /api/rooms/{room_id} 기능 구현
  .github/workflows/build-and-depoly-to-aws.yml
  BE/src/main/java/team13/kuje/airbnb/controller/EventController.java
  BE/src/main/java/team13/kuje/airbnb/controller/PlaceController.java
  BE/src/main/java/team13/kuje/airbnb/controller/RoomsController.java
  BE/src/main/java/team13/kuje/airbnb/controller/model/EventDto.java
  BE/src/main/java/team13/kuje/airbnb/controller/model/RoomDetailDto.java
  BE/src/main/java/team13/kuje/airbnb/controller/model/RoomDetailPriceDto.java
  BE/src/main/java/team13/kuje/airbnb/controller/model/WrapperDto.java
  BE/src/main/java/team13/kuje/airbnb/controller/model/WrapperDtoList.java
  BE/src/main/java/team13/kuje/airbnb/domain/Event.java
  BE/src/main/java/team13/kuje/airbnb/domain/Host.java
  BE/src/main/java/team13/kuje/airbnb/domain/Place.java
  BE/src/main/java/team13/kuje/airbnb/domain/ReservationGuest.java
  BE/src/main/java/team13/kuje/airbnb/domain/ReservationPeriod.java
  BE/src/main/java/team13/kuje/airbnb/domain/Room.java
  BE/src/main/java/team13/kuje/airbnb/domain/RoomImage.java
  BE/src/main/java/team13/kuje/airbnb/domain/RoomPrice.java
  BE/src/main/java/team13/kuje/airbnb/domain/RoomPriceInfo.java
  BE/src/main/java/team13/kuje/airbnb/repository/RoomsRepository.java
  BE/src/main/java/team13/kuje/airbnb/service/RoomsService.java
  BE/src/main/resources/application.yml
  BE/src/main/resources/db/data.sql
  BE/src/main/resources/db/schema.sql
  BE/src/test/java/team13/kuje/airbnb/acceptance/EventAcceptanceTest.java
  BE/src/test/java/team13/kuje/airbnb/acceptance/PlaceAcceptanceTest.java
  BE/src/test/java/team13/kuje/airbnb/acceptance/RoomsAcceptanceTest.java
  BE/src/test/java/team13/kuje/airbnb/domain/ReservationGuestTest.java
  BE/src/test/java/team13/kuje/airbnb/domain/ReservationPeriodTest.java
  BE/src/test/java/team13/kuje/airbnb/domain/RoomPriceTest.java
  BE/src/test/java/team13/kuje/airbnb/service/EventServiceTest.java
  BE/src/test/java/team13/kuje/airbnb/service/PlaceServiceTest.java
  BE/src/test/java/team13/kuje/airbnb/service/RoomsServiceTest.java
  BE/src/test/resources/application.yml
  BE/src/test/resources/testdb/data.sql
  BE/src/test/resources/testdb/schema.sql
Labels: feature, BE

#44 [BE] - PR 2-1 Review 반영
  BE/src/main/java/team13/kuje/airbnb/domain/Place.java
  BE/src/main/java/team13/kuje/airbnb/domain/Position.java
  BE/src/main/java/team13/kuje/airbnb/repository/PlaceRepository.java
  BE/src/main/java/team13/kuje/airbnb/repository/RoomsRepository.java
  BE/src/main/java/team13/kuje/airbnb/service/PlaceService.java
  BE/src/main/java/team13/kuje/airbnb/util/MapUtils.java
  BE/src/test/java/team13/kuje/airbnb/acceptance/EventAcceptanceTest.java
  BE/src/test/java/team13/kuje/airbnb/acceptance/RoomsAcceptanceTest.java
  BE/src/test/java/team13/kuje/airbnb/domain/RoomPriceTest.java
  BE/src/test/resources/application.yml
Labels: BE, refactor

#50 [BE] - application.yml 서버, 개발환경 분리, pub 서버에서 pri server MySQL 사용하도록 변경
  .github/workflows/build-and-depoly-to-aws.yml
  BE/Dockerfile
  BE/mysql-dev.yml
  BE/src/main/resources/application-dev.yml
  BE/src/main/resources/application-prod.yml
  BE/src/main/resources/application.yml
Labels: BE, deploy

#51 [BE] - PR 2-2 리뷰 적용 (불필요한 getter, 객체 제거, N+1 문제)
  BE/src/main/java/team13/kuje/airbnb/controller/model/RoomDetailDto.java
  BE/src/main/java/team13/kuje/airbnb/controller/model/RoomDetailPriceDto.java
  BE/src/main/java/team13/kuje/airbnb/domain/ReservationPeriod.java
  BE/src/main/java/team13/kuje/airbnb/domain/Room.java
  BE/src/main/java/team13/kuje/airbnb/domain/RoomPrice.java
  BE/src/main/java/team13/kuje/airbnb/service/RoomsService.java
  BE/src/test/java/team13/kuje/airbnb/domain/RoomPriceTest.java
Labels: fix, BE, refactor

#52 [BE] - GET /api/rooms?category_tag=list 기능 구현
  BE/src/main/java/team13/kuje/airbnb/controller/PlaceController.java
  BE/src/main/java/team13/kuje/airbnb/controller/RoomsController.java
  BE/src/main/java/team13/kuje/airbnb/controller/model/RoomDto.java
  BE/src/main/java/team13/kuje/airbnb/domain/Event.java
  BE/src/main/java/team13/kuje/airbnb/domain/Host.java
  BE/src/main/java/team13/kuje/airbnb/domain/Place.java
  BE/src/main/java/team13/kuje/airbnb/domain/Position.java
  BE/src/main/java/team13/kuje/airbnb/domain/Room.java
  BE/src/main/java/team13/kuje/airbnb/domain/RoomImage.java
  BE/src/main/java/team13/kuje/airbnb/domain/RoomPriceInfo.java
  BE/src/main/java/team13/kuje/airbnb/domain/RoomsHistogram.java
  BE/src/main/java/team13/kuje/airbnb/repository/EventRepository.java
  BE/src/main/java/team13/kuje/airbnb/repository/RoomsRepository.java
  BE/src/main/java/team13/kuje/airbnb/service/PlaceService.java
  BE/src/main/java/team13/kuje/airbnb/service/RoomsService.java
  BE/src/test/java/team13/kuje/airbnb/acceptance/EventAcceptanceTest.java
  BE/src/test/java/team13/kuje/airbnb/acceptance/PlaceAcceptanceTest.java
  BE/src/test/java/team13/kuje/airbnb/acceptance/RoomsAcceptanceTest.java
  BE/src/test/java/team13/kuje/airbnb/domain/PlaceTest.java
  BE/src/test/java/team13/kuje/airbnb/domain/PositionTest.java
  BE/src/test/java/team13/kuje/airbnb/domain/ReservationGuestTest.java
  BE/src/test/java/team13/kuje/airbnb/domain/ReservationPeriodTest.java
  BE/src/test/java/team13/kuje/airbnb/domain/RoomsHistogramTest.java
  BE/src/test/java/team13/kuje/airbnb/service/EventServiceTest.java
  BE/src/test/java/team13/kuje/airbnb/service/PlaceServiceTest.java
  BE/src/test/java/team13/kuje/airbnb/service/RoomsServiceTest.java
Labels: feature, BE

#53 [BE] - Hotfix 검색로직 범위 문제로 서버 부하
  .github/workflows/build-and-depoly-to-aws.yml
  BE/src/main/java/team13/kuje/airbnb/domain/Position.java
  BE/src/main/java/team13/kuje/airbnb/domain/RoomsHistogram.java
  BE/src/main/java/team13/kuje/airbnb/repository/RoomsRepository.java
  BE/src/main/java/team13/kuje/airbnb/service/PlaceService.java
Labels: fix, BE, deploy
