Repository jeremy0405/airbnb, pull requests merged in 2022-05, with the labels that each got.

#2 [공통] 프로젝트 소개 docs 추가
  README.md
Labels: documentation

#4 feat: Airbnb 프로젝트 생성 및 초기설정
  iOS/.gitignore
  iOS/AirbnbApp/.swiftlint.yml
  iOS/AirbnbApp/AirbnbApp.xcodeproj/project.pbxproj
  iOS/AirbnbApp/AirbnbApp.xcodeproj/project.xcworkspace/contents.xcworkspacedata
  iOS/AirbnbApp/AirbnbApp.xcodeproj/project.xcworkspace/xcshareddata/IDEWorkspaceChecks.plist
  iOS/AirbnbApp/AirbnbApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
  iOS/AirbnbApp/AirbnbApp/AppDelegate.swift
  iOS/AirbnbApp/AirbnbApp/Assets.xcassets/AccentColor.colorset/Contents.json
  iOS/AirbnbApp/AirbnbApp/Assets.xcassets/AppIcon.appiconset/Contents.json
  iOS/AirbnbApp/AirbnbApp/Assets.xcassets/Contents.json
  iOS/AirbnbApp/AirbnbApp/Base.lproj/LaunchScreen.storyboard
  iOS/AirbnbApp/AirbnbApp/Base.lproj/Main.storyboard
  iOS/AirbnbApp/AirbnbApp/Info.plist
  iOS/AirbnbApp/AirbnbApp/SceneDelegate.swift
  iOS/AirbnbApp/AirbnbApp/ViewController.swift
Labels: feature, iOS

#18 [BE] - 프로젝트 초기세팅
  BE/.gitignore
  BE/README.md
  BE/build.gradle
  BE/gradle/wrapper/gradle-wrapper.jar
  BE/gradle/wrapper/gradle-wrapper.properties
  BE/gradlew
  BE/gradlew.bat
  BE/settings.gradle
  BE/src/main/java/team13/kuje/airbnb/AirbnbApplication.java
  BE/src/main/resources/application.properties
  BE/src/test/java/team13/kuje/airbnb/AirbnbApplicationTests.java
Labels: BE

#20 [BE] - 이벤트 도메인 기능 구현
  BE/build.gradle
  BE/src/main/java/team13/kuje/airbnb/controller/EventController.java
  BE/src/main/java/team13/kuje/airbnb/controller/model/EventDto.java
  BE/src/main/java/team13/kuje/airbnb/controller/model/WrapperDto.java
  BE/src/main/java/team13/kuje/airbnb/domain/Event.java
  BE/src/main/java/team13/kuje/airbnb/repository/EventRepository.java
  BE/src/main/java/team13/kuje/airbnb/service/EventService.java
  BE/src/main/resources/application.yml
  BE/src/test/java/team13/kuje/airbnb/AirbnbApplicationTests.java
  BE/src/test/java/team13/kuje/airbnb/EventAcceptanceTest.java
  BE/src/test/java/team13/kuje/airbnb/service/EventServiceTest.java
Labels: feature, BE

#21 [BE] - 가까운 여행지 조회 기능
  BE/src/main/java/team13/kuje/airbnb/controller/EventController.java
  BE/src/main/java/team13/kuje/airbnb/controller/PlaceController.java
  BE/src/main/java/team13/kuje/airbnb/controller/model/PlaceDto.java
  BE/src/main/java/team13/kuje/airbnb/controller/model/WrapperDto.java
  BE/src/main/java/team13/kuje/airbnb/domain/Place.java
  BE/src/main/java/team13/kuje/airbnb/domain/Position.java
  BE/src/main/java/team13/kuje/airbnb/repository/PlaceRepository.java
  BE/src/main/java/team13/kuje/airbnb/service/PlaceService.java
  BE/src/main/java/team13/kuje/airbnb/util/MapUtils.java
  BE/src/test/java/team13/kuje/airbnb/acceptance/EventAcceptanceTest.java
  BE/src/test/java/team13/kuje/airbnb/acceptance/PlaceAcceptanceTest.java
  BE/src/test/java/team13/kuje/airbnb/domain/PlaceTest.java
  BE/src/test/java/team13/kuje/airbnb/domain/PositionTest.java
  BE/src/test/java/team13/kuje/airbnb/service/PlaceServiceTest.java
Labels: BE

#36 [iOS] SearchView 및 SearchBar 자동완성
  iOS/AirbnbApp/AirbnbApp.xcodeproj/project.pbxproj
  iOS/AirbnbApp/AirbnbApp/Source/Present/Search/PopularCollectionViewDataSource.swift
  iOS/AirbnbApp/AirbnbApp/Source/Present/Search/PopularHeaderView.swift
  iOS/AirbnbApp/AirbnbApp/Source/Present/Search/SearchBarDelegate.swift
  iOS/AirbnbApp/AirbnbApp/Source/Present/Search/SearchCollectionViewDataSource.swift
  iOS/AirbnbApp/AirbnbApp/Source/Present/Search/SearchResultViewCell.swift
  iOS/AirbnbApp/AirbnbApp/Source/Present/Search/SearchViewController.swift
  iOS/AirbnbApp/AirbnbApp/Source/Present/SearchHome/Support/SectionLayoutFactory.swift
Labels: feature, iOS, View

#37 [BE] - Getter 없어서 JSON안내려가는 버그 해결
  BE/src/main/java/team13/kuje/airbnb/controller/model/WrapperDto.java
Labels: fix

#38 [BE] - 더미데이터 추가
  BE/src/main/resources/application.properties
  BE/src/main/resources/application.yml
  BE/src/main/resources/data.sql
  BE/src/main/resources/schema.sql
Labels: feature, BE

#39 [BE] 더미데이터 추가에 따른 인수테스트 성공하도록 변경
  BE/src/main/java/team13/kuje/airbnb/service/PlaceService.java
  BE/src/main/resources/schema.sql
  BE/src/test/java/team13/kuje/airbnb/acceptance/EventAcceptanceTest.java
  BE/src/test/java/team13/kuje/airbnb/acceptance/PlaceAcceptanceTest.java
  BE/src/test/resources/application.yml
Labels: feature, BE

#40 [BE] - 서버에서 docker를 통한 배포를 위한 Dockerfile 생성
  BE/Dockerfile
Labels: BE, deploy
